(package "isortify"
         "0.0.1"
         "(automatically) format python buffers using isort")

(website-url "https://github.com/proofit404/isortify")
(keywords "convenience" "isort")

(package-file "isortify.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source 'gnu)
(source 'melpa)

(depends-on "emacs" "25")
(depends-on "pythonic")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
